server:
  port: 8094
spring:
  application:
    name: goods_page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.172.128
    username: wlkg
    password: 123456
    virtual-host: /wlkg


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}

wlkg:
  thymeleaf:
    destPath: D:/nginx-1.8.0/html/item - bak/html

